version: '3.8'

services:
  ckbt_mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: 'always'
    env_file:
      - .env
    ports:
      - '3306:3306'